# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b7d66415721970ccf7c4d39613f296e70b49bafd429bad8e2e04f535c2d4c8f2059a2723d09b040d531dc95e575a9691740ac3713480db333c8ebe9cd95b65

test:
  secret_key_base: e00fe38e15e3fe54a986a5203a53a58927eba86d7046817abee41949b53aa2248de3ffbea54e1592ffac17b3d9e3b2d90d5d58b054b1cf01698990857a583d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
